### PR TITLE
CHANGE main.js so it includes pre-transpiled code

### PR DESCRIPTION
**Pull request by ndelangen**
Using your package meant including coffeescript, with this change that's no longer necessary.

### CODE REVIEW

**Comment by searls** [comment]
Seems legit.

**Comment by searls** [comment]
Landed in 0.1.1

**Comment by liors** [comment]
@searls - this version bump actually started to brake my build w/ [launcher] Error: Error: Cannot find module './dist/jasmine-before-all'. To fix my build I had to rollback to version 0.1.0 - FYI

**Comment by searls** [comment]
Thanks @liors. I haven't used this thing in years so I didn't test this PR. I've fixed the issue and posted it at 0.1.2.

**Pull request merged**
